### ISSUE TITLE
Twitch now requires confirmation code sent to mail every time you login from a new place

### ISSUE THREAD

**Issue by ahmedtds** [kaneyxx/Twitch_Channel_Points_Clicker#1]
Can you update this to work with latest Twitch changes please?

Logging with username and password is not possible anymore because Twitch now requires you to enter confirmation code sent to mail when a cookie is not saved. And sometimes it asks some kind of captcha on top of that.

Can you make it so we can specify cookie or we can enter the required code and continue?

**Comment by kaneyxx** [comment]
hello~~ thanks for your message.
I have tried it again on my computer, and it still works fine.
I think I forgot leaving some important notes, so I add them to new README.
Please check it and try again. 

Possible issues:
1. Browser and its driver version not matching.
2. Not running in OS default terminal. (if you run it even in IDE's terminal, it still won't work)

If you still have any issue while running the files, please let me know. Thanks again :)

**Comment by kaneyxx** [comment]
> Can you update this to work with latest Twitch changes please?
> 
> Logging with username and password is not possible anymore because Twitch now requires you to enter confirmation code sent to mail when a cookie is not saved. And sometimes it asks some kind of captcha on top of that.
> 
> Can you make it so we can specify cookie or we can enter the required code and continue?

btw, you can also check this https://github.com/trmcnvn/twitch-channel-points
I think it would be more convenient to use than mine

**Comment by ahmedtds** [comment]
Oh damn I think I misunderstood function of this program. I thought this was a headless program but a browser window needs to stay open for it work right?

I need a console program that will work headless but this aint do it right?

Thank so you much for your answer btw.

**Comment by kaneyxx** [comment]
It's okay :)  Selenium module is running under headless browser...so....yeah it's quiet annoying. Might the chrome/firefox extension version would be helpful(?  
At least you don't need to enter account and password info every time. 
Recently I have no time to try to build other program for this. If you find anything about twitch channel points claiming, feel free to inform me :D  
I'm so glad to know that~ thanks !
